package com.uncle.csdn.entity;

import java.util.Date;

/**
 * columnist
 * 
 * @author bianj
 * @version 1.0.0 2020-08-20
 */
public class Columnist implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 2769835221521047061L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** name */
    private String name;

    /** intro */
    private String intro;

    /** blogCount */
    private Integer blogCount;

    /** createTime */
    private Date createTime;

    private Date updateTime;

    private int columnistState;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        return "Columnist{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", intro='" + intro + '\'' +
                ", blogCount=" + blogCount +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                ", columnistState=" + columnistState +
                '}';
    }

    public int getColumnistState() {
        return columnistState;
    }

    public void setColumnistState(int columnistState) {
        this.columnistState = columnistState;
    }

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取name
     * 
     * @return name
     */
    public String getName() {
        return this.name;
    }

    /**
     * 设置name
     * 
     * @param name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 获取intro
     * 
     * @return intro
     */
    public String getIntro() {
        return this.intro;
    }

    /**
     * 设置intro
     * 
     * @param intro
     */
    public void setIntro(String intro) {
        this.intro = intro;
    }

    /**
     * 获取blogCount
     * 
     * @return blogCount
     */
    public Integer getBlogCount() {
        return this.blogCount;
    }

    /**
     * 设置blogCount
     * 
     * @param blogCount
     */
    public void setBlogCount(Integer blogCount) {
        this.blogCount = blogCount;
    }

    /**
     * 获取createTime
     * 
     * @return createTime
     */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 设置createTime
     * 
     * @param createTime
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}